version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
      args:
        - MONGO_HOST=mongo
        - MONGO_PORT=27017
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    networks:
      - container-bridge
    ports:
      - 3001:3000

networks:
  container-bridge:
    name: container-bridge
    driver: bridge
