version: '3.8'

services:
  mongo:
    container_name: mongo
    build:
      context: ./mongodb
      dockerfile: dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/data:/var/lib/mongodb
      - ./mongodb/logs/log:/var/log/mongodb
    ports:
      - 27018:27017
    networks:
      - container-bridge
    restart: always

  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: dockerfile
    volumes:
      - ./redis/data:/data
    ports:
      - 6380:6379
    networks:
      - container-bridge
    restart: always

networks:
  container-bridge:
    name: container-bridge
    driver: bridge
