version: '3.8'

services:
  mongo:
    container_name: mongo
    build:
      context: ./mongodb
      dockerfile: dockerfile
    environment:
      TZ: Asia/Seoul
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/data:/var/lib/mongodb
      - ./mongodb/logs/log:/var/log/mongodb
    ports:
      - 27018:27017
    networks:
      - container-bridge
    restart: always

  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: dockerfile
    volumes:
      - ./redis/data:/data
    ports:
      - 6380:6379
    networks:
      - container-bridge
    restart: always

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: dockerfile
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: password
    command:
      - --bind-address=0.0.0.0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/disk:/disk
    ports:
      - 33061:3306
    networks:
      - container-bridge
    restart: always

networks:
  container-bridge:
    name: container-bridge
    driver: bridge
