version: '3.8'

services:
  mongo:
    container_name: mongo
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mongodb
      - ./logs/log:/var/log/mongodb
    ports:
      - 27018:27017
    restart: always
